version: '3.2'

services:

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - '5672:5672'
      - '15672:15672'
    volumes:
      - '~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/'
    env_file:
      - .env
    environment:
      - RABBITMQ_DEFAULT_USER=${SPRING_RABBITMQ_USERNAME}
      - RABBITMQ_DEFAULT_PASS=${SPRING_RABBITMQ_PASSWORD}
    restart: always
    networks:
      - appfoobar

networks:
  appfoobar:
    driver: bridge