version: '3.2'

services:

  postgresql:
    image: docker.io/bitnami/postgresql:13
    container_name: postgresql
    ports:
      - '5432:5432'
    volumes:
      - 'postgresql_data:/bitnami/postgresql'
      - './creata-database.sql:/docker-entrypoint-initdb.d/init-database.sql'
    env_file:
      - .env       
    environment:
      - POSTGRESQL_USERNAME=${SPRING_POSTGRES_USER}
      - POSTGRESQL_PASSWORD=${SPRING_POSTGRES_PASS}
    networks:
      - appfoobar

  sonarqube:
    image: docker.io/bitnami/sonarqube:9
    container_name: sonarqube
    ports:
      - '9000:9000'
    volumes:
      - 'sonarqube_data:/bitnami/sonarqube'
    env_file:
      - .env
    environment:
      - SONARQUBE_DATABASE_HOST=postgresql
      - SONARQUBE_DATABASE_PORT_NUMBER=5432
      - SONARQUBE_DATABASE_NAME=${POSTGRESQL_DATABASE_SONAR}
      - SONARQUBE_DATABASE_USER=${SPRING_POSTGRES_USER}
      - SONARQUBE_DATABASE_PASSWORD=${SPRING_POSTGRES_PASS}
      - SONARQUBE_USERNAME=${SONARQUBE_USER}
      - SONARQUBE_PASSWORD=${SONARQUBE_PASS}
    networks:
      - appfoobar

networks:
  appfoobar:
    driver: bridge

volumes:
  postgresql_data:
    driver: local
  sonarqube_data:
    driver: local