spring:
  rabbitmq:
    port: 5672
    host: localhost
    username: foobar
    password: An33ytG3Hln#
    routingkey: product_key
    queue: products
    exchange: products_exchange
  datasource:
    username: sa
    url: jdbc:h2:mem:liquibase;DB_CLOSE_ON_EXIT=FALSE
    password: ''
  jpa:
    show-sql: 'true'
  h2:
    console:
      enabled: 'true'
      path: /h2-console